import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { PipelineContext } from '../types.js';

// ---------------------------------------------------------------------------
// Nav helpers
// ---------------------------------------------------------------------------

function chapterNav(chapters: { number: number; title: string }[]): string {
  return chapters
    .map(ch => {
      const num = String(ch.number).padStart(2, '0');
      return `    - "Chapter ${ch.number}: ${ch.title}": chapters/chapter-${num}.md`;
    })
    .join('\n');
}

function quizNav(chapters: { number: number; title: string }[]): string {
  return chapters
    .map(ch => {
      const num = String(ch.number).padStart(2, '0');
      return `    - "Chapter ${ch.number} Quiz": quizzes/quiz-${num}.md`;
    })
    .join('\n');
}

function microsimNav(count: number): string {
  return Array.from({ length: count }, (_, i) => {
    const num = String(i + 1).padStart(2, '0');
    return `    - "MicroSim ${i + 1}": microsims/microsim-${num}.md`;
  }).join('\n');
}

// ---------------------------------------------------------------------------
// YAML builder
// ---------------------------------------------------------------------------

function buildMkdocsYaml(
  siteName: string,
  repoUrl: string,
  chapterList: { number: number; title: string }[],
  microsimCount: number,
): string {
  return `site_name: "${siteName}"
site_description: "An intelligent textbook with interactive simulations, knowledge graphs, and adaptive assessments."
site_author: "Generated by create-intelligent-textbook"
${repoUrl ? `repo_url: "${repoUrl}"` : ''}

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - toc.integrate

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: false

nav:
  - Home: index.md
  - Course Description: course-description.md
  - Chapters:
${chapterNav(chapterList)}
  - Glossary: glossary.md
  - MicroSims:
${microsimNav(microsimCount)}
  - Quizzes:
${quizNav(chapterList)}
  - Knowledge Graph:
    - Concept Map: learning-graph/concept-map.md
    - Dependencies: learning-graph/dependency-graph.md
    - Metrics: learning-graph/book-metrics.md
  - FAQ: faq.md
  - References: references.md
  - About: about.md
`;
}

// ---------------------------------------------------------------------------
// Extra CSS
// ---------------------------------------------------------------------------

const EXTRA_CSS = `:root {
  --md-primary-fg-color: #1a237e;
  --md-primary-fg-color--light: #3949ab;
  --md-primary-fg-color--dark: #0d1445;
  --md-accent-fg-color: #ff6d00;
}

/* Admonition tweaks */
.md-typeset .admonition,
.md-typeset details {
  border-radius: 6px;
}

/* Knowledge graph embed */
.graph-container {
  width: 100%;
  height: 600px;
  border: 1px solid var(--md-default-fg-color--lightest);
  border-radius: 8px;
  overflow: hidden;
}

/* MicroSim iframe */
.microsim-frame {
  width: 100%;
  height: 500px;
  border: none;
  border-radius: 8px;
}
`;

// ---------------------------------------------------------------------------
// Override template (minimal — just loads base)
// ---------------------------------------------------------------------------

const MAIN_HTML = `{% extends "base.html" %}
`;

// ---------------------------------------------------------------------------
// Home page
// ---------------------------------------------------------------------------

function buildIndexMd(title: string, subtitle: string, targetAudience: string): string {
  return `# ${title}

*${subtitle}*

## Welcome

${targetAudience || 'Welcome to this intelligent textbook. Use the navigation above to explore chapters, simulations, and assessments.'}

## How to Use This Textbook

This is an **intelligent textbook** — more than a static document. It includes:

- **Chapters** with in-depth explanations and worked examples
- **MicroSims** — interactive browser-based simulations you can run without any setup
- **Knowledge Graph** — a visual map of how concepts connect and build on each other
- **Quizzes** with instant feedback and detailed explanations
- **Glossary** with precise definitions
- **FAQ** covering the most common learner questions
- **References** curated by chapter

Use the tabs at the top to navigate between sections. The search bar (top right) works across all content.

!!! tip "Start here"
    Begin with the [Course Description](course-description.md) to understand the scope and prerequisites,
    then work through the chapters in order.
`;
}

// ---------------------------------------------------------------------------
// About page
// ---------------------------------------------------------------------------

function buildAboutMd(title: string, topic: string): string {
  return `# About This Textbook

## ${title}

This intelligent textbook was generated using [create-intelligent-textbook](https://github.com/Yarmoluk/create-intelligent-textbook),
a CLI tool that uses Claude (Anthropic) to produce complete, structured, interactive learning resources.

## Methodology

This textbook follows the **Intelligent Textbook** methodology:

- **Concept taxonomy** — every concept is tagged with a Bloom's Taxonomy level and mapped to its prerequisites
- **Knowledge graph** — concepts and their dependencies are visualized as an interactive graph
- **MicroSims** — each chapter includes a browser-based simulation to reinforce key ideas
- **Adaptive assessments** — quizzes are distributed across Bloom's levels for comprehensive coverage

## Topic

This textbook covers: **${topic}**

## License

This content is provided under the MIT License. You are free to adapt, share, and build upon it with attribution.

## Feedback

Found an error or have a suggestion? Open an issue on the repository associated with this textbook.
`;
}

// ---------------------------------------------------------------------------
// Main step
// ---------------------------------------------------------------------------

export default async function generateMkdocsConfig(ctx: PipelineContext): Promise<void> {
  const { topic, microsims, model: _model, repoName } = ctx.config;
  const title = ctx.courseDescription?.title ?? topic;
  const subtitle = ctx.courseDescription?.subtitle ?? '';
  const targetAudience = ctx.courseDescription?.targetAudience ?? '';

  const chapters = ctx.chapters ?? [];
  const chapterList =
    chapters.length > 0
      ? chapters.map(ch => ({ number: ch.number, title: ch.title }))
      : (ctx.courseDescription?.topics ?? []).map((t, i) => ({
          number: i + 1,
          title: t,
        }));

  const repoUrl = repoName
    ? `https://github.com/Yarmoluk/${repoName}`
    : '';

  const yaml = buildMkdocsYaml(title, repoUrl, chapterList, microsims);

  // Write mkdocs.yml at root of outputDir (NOT inside docs/)
  await writeFile(join(ctx.outputDir, 'mkdocs.yml'), yaml, 'utf8');

  // docs/css/extra.css
  const cssDir = join(ctx.outputDir, 'docs', 'css');
  await mkdir(cssDir, { recursive: true });
  await writeFile(join(cssDir, 'extra.css'), EXTRA_CSS, 'utf8');

  // docs/overrides/main.html
  const overridesDir = join(ctx.outputDir, 'docs', 'overrides');
  await mkdir(overridesDir, { recursive: true });
  await writeFile(join(overridesDir, 'main.html'), MAIN_HTML, 'utf8');

  // docs/index.md
  const docsDir = join(ctx.outputDir, 'docs');
  await mkdir(docsDir, { recursive: true });
  await writeFile(
    join(docsDir, 'index.md'),
    buildIndexMd(title, subtitle, targetAudience),
    'utf8',
  );

  // docs/about.md
  await writeFile(join(docsDir, 'about.md'), buildAboutMd(title, topic), 'utf8');
}
